#!/bin/bash
#buildAndRun: Script to build client and server, run the server and start parcel watch
#Created: Sun Jun  2 16:51:39 CDT 2019
thisDir=$(pwd)
cd ./AzulWeb/Client/ && parcel build index.html -d ../Server/wwwroot/
cd $thisDir && dotnet run --project ./AzulWeb/Server/Server.csproj
exit 0
