#!/bin/bash
#buildClient: Script to build the client code and put it in wwwroot
#Created: Sun Jun  2 16:44:39 CDT 2019
if [[ $1 == "debug" ]]; then
    parcel build index.html -d ../Server/wwwroot/ --no-minify
else
    parcel build index.html -d ../Server/wwwroot/
fi;
exit 0
